---
- name: install os packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ os_packages }}"

- name: configure autostart of squid with supervisord
  blockinfile:
    path: /etc/supervisord.conf
    block: |
      [program:squid]
      command=/usr/sbin/squid -N &
  register: supervisord

- name: set cache_dir to /Vagrant
  lineinfile:
    path: /etc/squid/squid.conf
    insertafter: '^#cache_dir '
    line: cache_dir ufs /vagrant/squid 3072 16 256
  register: squidconf

- name: Set max filesize to cache
  lineinfile:
    path: /etc/squid/squid.conf
    insertbefore: '^#cache_dir '
    line: maximum_object_size 100 MB

- name: start incrond via supervisord
  command: supervisorctl stop
  when: squidconf.changed

- name: create cache directories
  command: squid -z
  when: squidconf.changed

- name: start incrond via supervisord
  command: supervisorctl update
  when: supervisord.changed
